import { createWriteStream, readdir } from "fs";
import { basename, join as pathJoin, resolve } from "path";
import { promisify } from "util";

const readdirAsync = promisify(readdir);

/**
 * Any .tsx files to explicitly exclude (non-".tsx" files are never included)
 */
const EXCLUDE = ["stories.tsx"];

/**
 * Generates an "index.ts" file that acts as an entry-point by
 * exporting all of the default exports for all React components
 * in the given directory.
 *
 * @param rootPath The path of the components.
 */
const generateIndex = async (rootPath: string): Promise<void> => {
  const writeStream = createWriteStream(pathJoin(rootPath, "index.ts"));
  console.log(`Creating index.ts in ${rootPath}`);

  try {
    const files = await readdirAsync(rootPath);

    writeStream.write("/* eslint-disable prettier/prettier */\n");
    writeStream.write(
      "// This file is automatically generated by scripts/generateIndex.ts - do not modify it directly.\n\n"
    );

    const componentNames = files
      .filter(
        // Only React .tsx components.
        (name): boolean => name.endsWith(".tsx") && !EXCLUDE.includes(name)
      )
      .map(
        // Extract conponent name from filename
        (name): string => basename(name, ".tsx")
      )
      .sort();

    componentNames.forEach((componentName): void => {
      writeStream.write(
        `export { default as ${componentName} } from "./${componentName}";\n`
      );
    });
  } catch (err) {
    // console.error('Error gerr.message);
    console.error(err.message);
    console.trace(__filename);
  } finally {
    writeStream.end();
  }
};

generateIndex(resolve(__dirname, "../src/transformed"));
