import { join as pathJoin, resolve, basename } from "path";
import { createWriteStream, readdir } from "fs";
import { promisify } from "util";
import console = require("console");

const readdirAsync = promisify(readdir);

const EXCLUDE = ["index.ts", "stories.tsx"];

/**
 * Generates an "index.ts" file that acts as an entry-point by
 * exporting all of the default exports for all React components
 * in the given directory.
 *
 * @param rootPath The path of the components.
 */
const generateIndex = async (rootPath: string) => {
  let writeStream;

  console.log(`Creating index.ts in ${rootPath}`);

  try {
    const files = await readdirAsync(rootPath);

    writeStream = createWriteStream(pathJoin(rootPath, "index.ts"));
    writeStream.write(
      "// This file is automatically generated by scripts/generateIndex.ts - do not modify it directly.\n\n"
    );

    const componentNames = files
      .filter(name => !EXCLUDE.includes(name)) // Only React .tsx components.
      .map(name => basename(name, ".tsx")) // Extract conponent name from filename
      .sort();

    componentNames.forEach(componentName => {
      writeStream.write(
        `export { default as ${componentName} } from "./${componentName}";\n`
      );
    });
  } catch (err) {
    console.error(err.message);
  } finally {
    if (writeStream) {
      writeStream.end();
    }
  }
};

generateIndex(resolve(__dirname, "../src/"));
