name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.14]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: npm install, build, and test
        run: |
          yarn
          yarn run build
          yarn test
        env:
          CI: true
      - name: Update Storybook
        if: success() && github.ref == 'refs/heads/master'
        run: |
          cd packages/uikit-storybook/dist
          git init
          git add .
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"
          git commit -m "docs(storybook): update gh-pages with latest storybook"
          git push --force --quiet "https://${{ secrets.GHPAGES_PUBLISH_TOKEN }}@github.com/${{ github.repository	}}" master:gh-pages
